### ISSUE TITLE
Licencie o projeto sob uma licença compatível com CC BY-SA 4.0

### ISSUE THREAD

**Issue by fer22f** [samuraiwesleyjack/Algos#1]
O projeto em inglês está licenciado sob a licença CC BY-SA 4.0: https://github.com/e-maxx-eng/e-maxx-eng/blob/master/LICENSE. Seus detalhes podem ser encontrados aqui: https://creativecommons.org/licenses/by-sa/4.0/deed.pt_BR.

Se você estiver adaptando o material em inglês (o que eu imagino que você esteja fazendo ao traduzí-lo), o seu projeto **deve** ter uma licença compatível com a original (e não a licença atual que é a padrão de copyright), e a mais indicada é a mesma licença, a CC BY-SA 4.0.

**Comment by samuraiwesleyjack** [comment]
Atualizei a licença para a CC BY-SA 4.0 (a mesma do projeto em inglês). 
Obrigado pelo comentário e perdão pela demora.
